name: Trigger auto deployment for container-app-dj3capom7fyum

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-dj3capom7fyum-AutoDeployTrigger-f8693cdf-e32a-4bd0-b0ce-e925b1e28e96.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDJ3CAPOM7FYUM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDJ3CAPOM7FYUM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDJ3CAPOM7FYUM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrydj3capom7fyum.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPDJ3CAPOM7FYUM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDJ3CAPOM7FYUM_REGISTRY_PASSWORD }}
          containerAppName: container-app-dj3capom7fyum
          resourceGroup: fastifyhello92bc
          imageToBuild: containerregistrydj3capom7fyum.azurecr.io/container-app-dj3capom7fyum:${{ github.sha }}
          


